### ISSUE TITLE
Rhadeihan Legs Error

### ISSUE THREAD

**Issue by Ender19** [Aegonian/ElithianAllianceStarboundMod#1]
Rhadeihan Legs displays the thruster animation while falling as a distortion sphere.
I don't know if this can be fixed, but i'm bringing it to your attention nonetheless.

**Comment by Aegonian** [comment]
I noticed the same issue when using the Wall Jump tech: while sliding along a wall, the boosters will remain activated while the feet are in different positions. I'm investigating if a fix is possible, but so far, a fix seems impossible. There doesn't appear to be a way to tell if a player is using a tech, and while I could modify the tech to make this possible, that could cause compatibility issues...

**Comment by Ender19** [comment]
Well, that's unfortunate. Lets hope there is a solution!

**Comment by Victorio-bb** [comment]
Make a separate mod for messing with the techs.

**Comment by Aegonian** [comment]
Hmm yeah, that could work! The mod will obviously have to be fully optional, but it would be a nice way to fix the issue for those players who don't use other mods that change techs!

**Comment by Aegonian** [comment]
Changes to the script now allow the Rhadeihan Legs to detect when the player is in an active movement ability, which is the case while in a distortion sphere. Issue should be resolved in most circumstances.
