### ISSUE TITLE
Folder spelled incorrectly

### ISSUE THREAD

**Issue by VarekRaith** [Aegonian/ElithianAllianceStarboundMod#2]
The folder 'levelling' is spelled incorrectly.
Should be 'leveling'.

**Comment by Aegonian** [comment]
For folder names, I tend to stick to using the same names found in the vanilla Starbound files, and vanilla Starbound uses the American spelling of "leveling" instead of British "levelling". Keeping folder names consistent with the main game helps prevent issues, so I won't be changing this one.
