### ISSUE TITLE
Creom->theauniquefooter

### ISSUE THREAD

**Issue by jtgibson01** [Aegonian/ElithianAllianceStarboundMod#7]
@Aegonian The typoflage that was applied in 2.3.4 to the Creon Embassy Teleporter [munged the descriptions pretty badly](https://github.com/Aegonian/ElithianAllianceStarboundMod/blame/master/objects/teleporter/creonembassyteleporter/creonembassyteleporter.object).

**Comment by Aegonian** [comment]
Fixed the issue in the latest GitHub update!
